version: '2'
services:
  harbor-setupwrapper:
    image: randrades/harbor-setupwrapper:1.4.0
    container_name: harbor-setupwrapper
    environment:
      #- HARBORHOSTNAME=${harborhostname}
      #- HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - HARBORHOSTNAME=reg.local
      - HARBOR_ADMIN_PASSWORD=Digicade%Admin001
    volumes:
      - vl-harbor-config-adminserver:/config-adminserver
      - vl-harbor-config-db:/config-db
      - vl-harbor-config-jobservice:/config-jobservice
      - vl-harbor-config-log:/config-log
      - vl-harbor-config-nginx:/config-nginx
      - vl-harbor-config-registry:/config-registry
      - vl-harbor-config-ui:/config-ui
    command: ["/harbor/harbor-setupwrapper.sh"]
    network_mode: "none"
    labels:
      #io.rancher.scheduler.affinity:host_label: ${harborhostlabel}
      io.rancher.scheduler.affinity:host_label: reg.local
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  log:
    image: vmware/harbor-log:v1.4.0
    container_name: harbor-log 
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - vl-harbor-configlog:/etc/logrotate.d/:z
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
  registry:
    image: vmware/registry-photon:v2.6.2-v1.4.0
    container_name: registry
    restart: always
    volumes:
      - vl-harbor-data-registry:/storage:z
      - vl-harbor-etcregistry:/etc/registry/:z
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    image: vmware/harbor-db:v1.4.0
    container_name: harbor-db
    restart: always
    volumes:
      - vl-harbor-data-database:/var/lib/mysql:z
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:v1.4.0
    container_name: harbor-adminserver
    restart: always
    volumes:
      - vl-harbor-data-config:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.4.0
    container_name: harbor-ui
    restart: always
    volumes:
      - ./common/config/ui/app.conf:/etc/ui/app.conf:z
      - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - ./common/config/ui/certificates/:/etc/ui/certificates/:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
      - /data/psc/:/etc/ui/token/:z
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.4.0
    container_name: harbor-jobservice
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - ./common/config/jobservice/app.conf:/etc/jobservice/app.conf:z
      - /data/secretkey:/etc/jobservice/key:z
    networks:
      - harbor
    depends_on:
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  proxy:
    image: vmware/nginx-photon:v1.4.0
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false
volumes:
  vl-harbor-etcjobservice:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-adminserver:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-db:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-jobservice:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-log:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-nginx:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-registry:
    #external: true
    #driver: ${volumedriver}
  vl-harbor-config-ui:
    #external: true
    #driver: ${volumedriver}